import type { Metadata } from "next";
import '@radix-ui/themes/styles.css';
import "./theme.config.css";
import "./globals.css";
import { Inter } from "next/font/google";
import NavBar from "./NavBar";
import { Container, Theme, ThemePanel } from '@radix-ui/themes';

const inter = Inter({ 
  subsets: ["latin"], 
  variable: '--font-inter',

});


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.variable}>
        <Theme  accentColor="violet" grayColor="gray">
          <NavBar/>
          <main className="container mx-auto px-4">
            <Container>{children}</Container>
          </main>
          {/* <ThemePanel /> */} 
        </Theme>
      </body>
    </html>
  );
}
